# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  slack: circleci/slack@4.8.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  notify:
    docker:
      - image: "cimg/base:stable"
    working_directory: ./tmp
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Foo!"
          command: |
            if grep "success" ./tmp/result.txt >/dev/null; then
              echo success
            else
              raise
            fi
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":circleci: *CircleCI job rspec is passed* :large_green_circle:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":raised_hand: *Author*: $CIRCLE_PR_USERNAME(Blank if not forked)\n:octocat: *URL*: $CIRCLE_PULL_REQUEST"
                  }
                }
              ]
            }
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":circleci: *CircleCI job rspec is failed* :red_circle:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":raised_hand: *Author*: $CIRCLE_PR_USERNAME(Blank if not forked)\n:octocat: *URL*: $CIRCLE_PULL_REQUEST"
                  }
                }
              ]
            }
  save-status:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    working_directory: ./tmp
    steps:
      - run:
          name: "Say hello"
          command: |
            echo "Hello, World!"
      - run:
          name: "Save success"
          when: on_success
          command: |
            mkdir ./tmp/
            echo "success" > ./tmp/result.txt
      - run:
          name: "Save fail"
          when: on_fail
          command: |
            mkdir ./tmp/
            echo "fail" > ./tmp/result.txt
      - persist_to_workspace:
          root: .
          paths:
            - ./tmp/result.txt

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  save-status-workflow:
    jobs:
      - save-status
      - notify:
          context: slack-secrets
          requires:
            - save-status
